title: "The PEAK Guidebook"
description: "Comprehensive, community‑maintained reference for the PEAK expedition survival game."
remote_theme: just-the-docs/just-the-docs
color_scheme: "dark"
search_enabled: true
